[theme]
base="light"
primaryColor="#03436D"
textColor="#102030"
baseRadius="full"
buttonRadius="0.2rem"
backgroundColor = "#e7f0f4"
secondaryBackgroundColor="#f2f2f2"
borderColor="#1e3d58"
showWidgetBorder=false